syntax = "proto3";

package shared.messages.v1;

option go_package = "gymbo.stixman.co/shared/gen/messages/v1";

import "shared/entities/v1/client.proto";

message GetClientRequest {
  string id = 1;
}

message GetClientResponse {
  shared.entities.v1.Client client = 1;
}

message ListClientsRequest {
  int32 index = 1;
  int32 limit = 2;
  int32 offset = 3;
  map<string, string> filters = 4;
  map<string, string> sort = 5;
}

message ListClientsResponse {
  repeated shared.entities.v1.Client clients = 1;
  int32 total = 2;
  int32 page = 3;
  int32 limit = 4;
  int32 offset = 5;
}

message CreateClientRequest {
  shared.entities.v1.Client client = 1;
}

message CreateClientResponse {
  shared.entities.v1.Client client = 1;
}

message UpdateClientRequest {
  shared.entities.v1.Client client = 1;
}

message UpdateClientResponse {
  shared.entities.v1.Client client = 1;
}

message DeleteClientRequest {
  string id = 1;
}

message DeleteClientResponse {}