syntax = "proto3";

package shared.messages.v1;

option go_package = "gymbo.stixman.co/shared/gen/messages/v1";

import "shared/entities/v1/exercise.proto";
import "shared/entities/v1/media.proto";
import "shared/entities/v1/client.proto";
import "shared/entities/v1/organisation.proto";
import "shared/entities/v1/trainer.proto";
import "shared/entities/v1/assessment.proto";

message ExtendedExercise {
  shared.entities.v1.Client client = 1;
  shared.entities.v1.Exercise exercise = 2;
  repeated shared.entities.v1.Media media = 3;
  repeated shared.entities.v1.Assessment assessments = 5;
}

message ExtendedNewExercise {
  shared.entities.v1.NewExercise new_exercise = 1;
  repeated shared.entities.v1.NewMedia new_media = 2;
}

message GetExerciseRequest {
  string id = 1;
}

message GetExerciseResponse {
  ExtendedExercise exercise = 1;
}

message ListExercisesRequest {
  int32 index = 1;
  int32 limit = 2;
  int32 offset = 3;
  map<string, string> filters = 4;
  map<string, string> sort = 5;
}

message ListExercisesResponse {
  repeated ExtendedExercise exercises = 1;
  int32 total = 2;
  int32 page = 3;
  int32 limit = 4;
  int32 offset = 5;
}

message CreateExerciseRequest {
  ExtendedNewExercise new_exercise = 1;
}

message CreateExerciseResponse {
  ExtendedExercise exercise = 1;
}

message UpdateExerciseRequest {
}

message UpdateExerciseResponse {
}

message DeleteExerciseRequest {
  string id = 1;
}

message DeleteExerciseResponse {}