// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file shared/entities/v1/client.proto (package shared.entities.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/entities/v1/client.proto.
 */
export const file_shared_entities_v1_client: GenFile = /*@__PURE__*/
  fileDesc("Ch9zaGFyZWQvZW50aXRpZXMvdjEvY2xpZW50LnByb3RvEhJzaGFyZWQuZW50aXRpZXMudjEi0AQKBkNsaWVudBIKCgJpZBgBIAEoCRINCgVlbWFpbBgCIAEoCRIRCglmdWxsX25hbWUYAyABKAkSFwoKZmlyc3RfbmFtZRgEIAEoCUgAiAEBEhYKCWxhc3RfbmFtZRgFIAEoCUgBiAEBEg4KBmdlbmRlchgGIAEoCRI2CgZoZWlnaHQYByABKAsyIS5zaGFyZWQuZW50aXRpZXMudjEuQ2xpZW50LkhlaWdodEgCiAEBEjYKBndlaWdodBgIIAEoCzIhLnNoYXJlZC5lbnRpdGllcy52MS5DbGllbnQuV2VpZ2h0SAOIAQESLgoKY3JlYXRlZF9hdBgJIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgKIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKZGVsZXRlZF9hdBgLIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAaJQoGSGVpZ2h0Eg0KBXZhbHVlGAEgASgNEgwKBHVuaXQYAiABKAkaJQoGV2VpZ2h0Eg0KBXZhbHVlGAEgASgNEgwKBHVuaXQYAiABKAkiVgoGR2VuZGVyEhYKEkdFTkRFUl9VTlNQRUNJRklFRBAAEg8KC0dFTkRFUl9NQUxFEAESEQoNR0VOREVSX0ZFTUFMRRACEhAKDEdFTkRFUl9PVEhFUhADQg0KC19maXJzdF9uYW1lQgwKCl9sYXN0X25hbWVCCQoHX2hlaWdodEIJCgdfd2VpZ2h0QrgBChZjb20uc2hhcmVkLmVudGl0aWVzLnYxQgtDbGllbnRQcm90b1ABWidneW1iby5zdGl4bWFuLmNvL3NoYXJlZC9nZW4vZW50aXRpZXMvdjGiAgNTRViqAhJTaGFyZWQuRW50aXRpZXMuVjHKAhJTaGFyZWRcRW50aXRpZXNcVjHiAh5TaGFyZWRcRW50aXRpZXNcVjFcR1BCTWV0YWRhdGHqAhRTaGFyZWQ6OkVudGl0aWVzOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message shared.entities.v1.Client
 */
export type Client = Message<"shared.entities.v1.Client"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string full_name = 3;
   */
  fullName: string;

  /**
   * @generated from field: optional string first_name = 4;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 5;
   */
  lastName?: string;

  /**
   * @generated from field: string gender = 6;
   */
  gender: string;

  /**
   * @generated from field: optional shared.entities.v1.Client.Height height = 7;
   */
  height?: Client_Height;

  /**
   * @generated from field: optional shared.entities.v1.Client.Weight weight = 8;
   */
  weight?: Client_Weight;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 9;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 10;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp deleted_at = 11;
   */
  deletedAt?: Timestamp;
};

/**
 * Describes the message shared.entities.v1.Client.
 * Use `create(ClientSchema)` to create a new message.
 */
export const ClientSchema: GenMessage<Client> = /*@__PURE__*/
  messageDesc(file_shared_entities_v1_client, 0);

/**
 * @generated from message shared.entities.v1.Client.Height
 */
export type Client_Height = Message<"shared.entities.v1.Client.Height"> & {
  /**
   * @generated from field: uint32 value = 1;
   */
  value: number;

  /**
   * @generated from field: string unit = 2;
   */
  unit: string;
};

/**
 * Describes the message shared.entities.v1.Client.Height.
 * Use `create(Client_HeightSchema)` to create a new message.
 */
export const Client_HeightSchema: GenMessage<Client_Height> = /*@__PURE__*/
  messageDesc(file_shared_entities_v1_client, 0, 0);

/**
 * @generated from message shared.entities.v1.Client.Weight
 */
export type Client_Weight = Message<"shared.entities.v1.Client.Weight"> & {
  /**
   * @generated from field: uint32 value = 1;
   */
  value: number;

  /**
   * @generated from field: string unit = 2;
   */
  unit: string;
};

/**
 * Describes the message shared.entities.v1.Client.Weight.
 * Use `create(Client_WeightSchema)` to create a new message.
 */
export const Client_WeightSchema: GenMessage<Client_Weight> = /*@__PURE__*/
  messageDesc(file_shared_entities_v1_client, 0, 1);

/**
 * @generated from enum shared.entities.v1.Client.Gender
 */
export enum Client_Gender {
  /**
   * @generated from enum value: GENDER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GENDER_MALE = 1;
   */
  MALE = 1,

  /**
   * @generated from enum value: GENDER_FEMALE = 2;
   */
  FEMALE = 2,

  /**
   * @generated from enum value: GENDER_OTHER = 3;
   */
  OTHER = 3,
}

/**
 * Describes the enum shared.entities.v1.Client.Gender.
 */
export const Client_GenderSchema: GenEnum<Client_Gender> = /*@__PURE__*/
  enumDesc(file_shared_entities_v1_client, 0, 0);

