// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file shared/entities/v1/organisation.proto (package shared.entities.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/entities/v1/organisation.proto.
 */
export const file_shared_entities_v1_organisation: GenFile = /*@__PURE__*/
  fileDesc("CiVzaGFyZWQvZW50aXRpZXMvdjEvb3JnYW5pc2F0aW9uLnByb3RvEhJzaGFyZWQuZW50aXRpZXMudjEihgIKDE9yZ2FuaXNhdGlvbhIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEg0KBWVtYWlsGAMgASgJEg8KB2FkZHJlc3MYBCABKAkSDQoFcGhvbmUYBSABKAkSDAoEbG9nbxgGIAEoCRIPCgd3ZWJzaXRlGAcgASgJEi4KCmNyZWF0ZWRfYXQYCCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCmRlbGV0ZWRfYXQYCiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQr4BChZjb20uc2hhcmVkLmVudGl0aWVzLnYxQhFPcmdhbmlzYXRpb25Qcm90b1ABWidneW1iby5zdGl4bWFuLmNvL3NoYXJlZC9nZW4vZW50aXRpZXMvdjGiAgNTRViqAhJTaGFyZWQuRW50aXRpZXMuVjHKAhJTaGFyZWRcRW50aXRpZXNcVjHiAh5TaGFyZWRcRW50aXRpZXNcVjFcR1BCTWV0YWRhdGHqAhRTaGFyZWQ6OkVudGl0aWVzOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message shared.entities.v1.Organisation
 */
export type Organisation = Message<"shared.entities.v1.Organisation"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string address = 4;
   */
  address: string;

  /**
   * @generated from field: string phone = 5;
   */
  phone: string;

  /**
   * @generated from field: string logo = 6;
   */
  logo: string;

  /**
   * @generated from field: string website = 7;
   */
  website: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 9;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp deleted_at = 10;
   */
  deletedAt?: Timestamp;
};

/**
 * Describes the message shared.entities.v1.Organisation.
 * Use `create(OrganisationSchema)` to create a new message.
 */
export const OrganisationSchema: GenMessage<Organisation> = /*@__PURE__*/
  messageDesc(file_shared_entities_v1_organisation, 0);

