services:
  minio:
    image: minio/minio:latest
    command: minio server --address ":9000" --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - gymbo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: qwertyui
      MINIO_DEFAULT_BUCKET: gymbo
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
      MINIO_SERVER_URL: http://localhost:9000

  mongo:
    image: mongo:8.2.6-rc0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: local
      MONGO_INITDB_DATABASE: gymbo
    restart: 'no'
    networks:
      - gymbo
volumes:
  minio:
    driver: local
  mongo-data:
    driver: local

networks:
  gymbo:
    driver: bridge