services:
  caddy:
    image: caddy
    build:
      context: .
      dockerfile: caddy.dockerfile
    ports:
      - "443:443"
    environment:
      # - DOMAIN=localhost
      - DOMAIN=gymbo.stixman.co
      - BACKEND_HOST=gradio
      - BACKEND_PORT=7860
    networks:
      - gymbo

  gradio:
    image: gradio
    build:
      context: .
      dockerfile: gradio.dockerfile
    ports:
      - "7860:7860"
    environment:
      - USER=admin
      - PASSWORD=sayplease
      - LIVEKIT_URL=http://livekit:7880
      - LIVEKIT_API_KEY=devsecret
      - LIVEKIT_API_SECRET=secret
      - S3_ACCESS_KEY=dummy
      - S3_SECRET=dummy
    networks:
      - gymbo

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - gymbo

  mongo:
    image:  mongodb/mongodb-community-server:8.0.4-ubi9
    ports:
      - "27017:27017"
    networks:
      - gymbo
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=local

  minio:
    image: quay.io/minio/minio:latest
    command: server --address ":9000" --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - gymbo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: qwertyui
      MINIO_DEFAULT_BUCKET: gymbo

volumes:
  minio:
    driver: local
  mongo-db:
    driver: local
  data:
    driver: local


networks:
  gymbo:
    driver: bridge
  host:
    driver: host