image := "ghcr.io/marco-leee/gymbo/pose:yolov26"
build-pose version:
    docker build --platform linux/amd64 -f Dockerfile.video-worker -t {{image}}-{{version}} .
    docker push {{image}}-{{version}}