[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "Marco Lee",email = "marco.lee@datax.io"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv (>=1.0.1,<2.0.0)",
    "numpy (<2)",
    "pandas (>=2.2.3,<3.0.0)",
    "pymongo (>=4.11,<5.0)",
    "pydantic (>=2.10.6,<3.0.0)",
    "pydantic-extra-types (>=2.10.2,<3.0.0)",
    "opencv-python (>=4.11.0.86,<5.0.0.0)",
    "mediapipe (>=0.10.21,<0.11.0)",
    "gradio (>=5.15.0,<6.0.0)",
    "python-ulid (>=3.0.0,<4.0.0)",
    "boto3 (>=1.36.16,<2.0.0)",
    "livekit (<0.20)",
    "livekit-agents (>=0.12.11,<0.13.0)"
]

[project.scripts]
agent = "python agent.py dev"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false