// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file gateways/admin/v1/admin_gateway.proto (package gateways.admin.v1, syntax proto3)
/* eslint-disable */

import { AdminGatewayService } from "./admin_gateway_pb";

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.Login
 */
export const login = AdminGatewayService.method.login;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.GetCurrentUser
 */
export const getCurrentUser = AdminGatewayService.method.getCurrentUser;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.RefreshToken
 */
export const refreshToken = AdminGatewayService.method.refreshToken;

/**
 * Organisation
 *
 * @generated from rpc gateways.admin.v1.AdminGatewayService.GetOrganisation
 */
export const getOrganisation = AdminGatewayService.method.getOrganisation;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.CreateOrganisation
 */
export const createOrganisation = AdminGatewayService.method.createOrganisation;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.UpdateOrganisation
 */
export const updateOrganisation = AdminGatewayService.method.updateOrganisation;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.DeleteOrganisation
 */
export const deleteOrganisation = AdminGatewayService.method.deleteOrganisation;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.ListOrganisations
 */
export const listOrganisations = AdminGatewayService.method.listOrganisations;

/**
 * Client
 *
 * @generated from rpc gateways.admin.v1.AdminGatewayService.GetClient
 */
export const getClient = AdminGatewayService.method.getClient;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.CreateClient
 */
export const createClient = AdminGatewayService.method.createClient;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.UpdateClient
 */
export const updateClient = AdminGatewayService.method.updateClient;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.DeleteClient
 */
export const deleteClient = AdminGatewayService.method.deleteClient;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.ListClients
 */
export const listClients = AdminGatewayService.method.listClients;

/**
 * Trainer
 *
 * @generated from rpc gateways.admin.v1.AdminGatewayService.GetTrainer
 */
export const getTrainer = AdminGatewayService.method.getTrainer;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.CreateTrainer
 */
export const createTrainer = AdminGatewayService.method.createTrainer;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.UpdateTrainer
 */
export const updateTrainer = AdminGatewayService.method.updateTrainer;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.DeleteTrainer
 */
export const deleteTrainer = AdminGatewayService.method.deleteTrainer;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.ListTrainers
 */
export const listTrainers = AdminGatewayService.method.listTrainers;

/**
 * Exercise
 *
 * @generated from rpc gateways.admin.v1.AdminGatewayService.GetExercise
 */
export const getExercise = AdminGatewayService.method.getExercise;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.CreateExercise
 */
export const createExercise = AdminGatewayService.method.createExercise;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.UpdateExercise
 */
export const updateExercise = AdminGatewayService.method.updateExercise;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.DeleteExercise
 */
export const deleteExercise = AdminGatewayService.method.deleteExercise;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.ListExercises
 */
export const listExercises = AdminGatewayService.method.listExercises;

/**
 * Assessment
 *
 * @generated from rpc gateways.admin.v1.AdminGatewayService.GetAssessment
 */
export const getAssessment = AdminGatewayService.method.getAssessment;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.CreateAssessment
 */
export const createAssessment = AdminGatewayService.method.createAssessment;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.UpdateAssessment
 */
export const updateAssessment = AdminGatewayService.method.updateAssessment;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.DeleteAssessment
 */
export const deleteAssessment = AdminGatewayService.method.deleteAssessment;

/**
 * @generated from rpc gateways.admin.v1.AdminGatewayService.ListAssessments
 */
export const listAssessments = AdminGatewayService.method.listAssessments;

/**
 * Media
 *
 * @generated from rpc gateways.admin.v1.AdminGatewayService.SignMediaUpload
 */
export const signMediaUpload = AdminGatewayService.method.signMediaUpload;
