syntax = "proto3";

package shared.entities.v1;

option go_package = "gymbo.stixman.co/shared/gen/entities/v1";

import "google/protobuf/timestamp.proto";

enum ExerciseType {
  EXERCISE_TYPE_UNSPECIFIED = 0;
  EXERCISE_TYPE_SQUAT = 1;
  EXERCISE_TYPE_LUNGE = 2;
  EXERCISE_TYPE_PUSH_UP = 3;
}

message Exercise {
  string id = 1;
  string client_id = 2;
  optional string assessment_id = 3;
  string media_id = 4;
  string name = 5;
  string description = 6;
  ExerciseType type = 7;
  string comment = 8;
  map<string, string> angles_of_interest_enum = 9;
  map<string, Angle> angles_of_interest = 10;
  map<string, Landmark2dResult> landmark_2d_results = 11;
  map<string, Landmark3dResult> landmark_3d_results = 12;
  google.protobuf.Timestamp created_at = 13;
  google.protobuf.Timestamp updated_at = 14;
  google.protobuf.Timestamp deleted_at = 15;
}

message Angle {
  int32 idx = 1;
  int32 degree = 2;
}

message Landmark2dResult {
  int32 idx = 1;
  float x = 2;
  float y = 3;
  float x_score = 4;
  float y_score = 5;
}

message Landmark3dResult {
  int32 idx = 1;
  float score = 2;
  float x = 3;
  float y = 4;
  float z = 5;
}

message NewExercise {
  string name = 1;
  string client_id = 2;
  optional string assessment_id = 3;
  optional string description = 4;
  ExerciseType type = 5;
  optional string comment = 6;
}