syntax = "proto3";

package shared.entities.v1;

option go_package = "gymbo.stixman.co/shared/gen/entities/v1";

import "google/protobuf/timestamp.proto";

import "shared/entities/v1/exercise.proto";

enum CameraView {
  CAMERA_VIEW_UNSPECIFIED = 0;
  CAMERA_VIEW_FRONT = 1;
  CAMERA_VIEW_BACK = 2;
  CAMERA_VIEW_LEFT = 3;
  CAMERA_VIEW_RIGHT = 4;
  CAMERA_VIEW_TOP = 5;
  CAMERA_VIEW_BOTTOM = 6;
}

enum Steps {
  STEP_UNSPECIFIED = 0;
  STEP_QUEUING = 1;
  STEP_INITIALIZING = 2;
  STEP_PREPROCESSING = 3;
  STEP_PROCESSING = 4;
  STEP_POSTPROCESSING = 5;
  STEP_FINALISING = 6;
  STEP_COMPLETED = 7;
}

message AnglesOfInterestEnum {
  message Enum {
    repeated int32 enum = 1;
  }

  map<string, Enum> enums = 1;
}

message Media {
  string id = 1;
  string exercise_id = 2;
  Steps step = 3;
  CameraView camera_view = 4;
  string original_video_location = 5;
  string processed_video_location = 6;
  string pose_detection_model_name = 7;
  map<string, string> metadata = 8;
  map<string, string> errors = 9;
  AnglesOfInterestEnum angles_of_interest_enum = 10;
  repeated AngleOfInterest angles_of_interest = 11;
  repeated Landmark2dResults landmark_2d_results = 12;
  repeated Landmark3dResults landmark_3d_results = 13;
  google.protobuf.Timestamp completed_at = 14;
  google.protobuf.Timestamp created_at = 15;
  google.protobuf.Timestamp updated_at = 16;
  google.protobuf.Timestamp deleted_at = 17;
}

message NewMedia {
  CameraView camera_view = 1;
  string original_video_location = 2;
  map<string, string> metadata = 3;
}


message Angle {
  int32 degree = 1;
  string comment = 2;
}

message AngleOfInterest {
  map<string, Angle> angles = 1;
}

message Landmark2dResult {
  int32 idx = 1;
  float x = 2;
  float y = 3;
  float x_score = 4;
  float y_score = 5;
}

message Landmark2dResults {
  repeated Landmark2dResult results = 1;
}

message Landmark3dResult {
  int32 idx = 1;
  float score = 2;
  float x = 3;
  float y = 4;
  float z = 5;
}

message Landmark3dResults {
  repeated Landmark3dResult results = 1;
}

message AsyncMediaProcessingQueueMessage {
  shared.entities.v1.Exercise exercise = 1;
  Media media = 2;
}