// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file shared/messages/v1/assessment.proto (package shared.messages.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/messages/v1/assessment.proto.
 */
export const file_shared_messages_v1_assessment: GenFile = /*@__PURE__*/
  fileDesc("CiNzaGFyZWQvbWVzc2FnZXMvdjEvYXNzZXNzbWVudC5wcm90bxISc2hhcmVkLm1lc3NhZ2VzLnYxIhYKFEdldEFzc2Vzc21lbnRSZXF1ZXN0IhcKFUdldEFzc2Vzc21lbnRSZXNwb25zZSIZChdDcmVhdGVBc3Nlc3NtZW50UmVxdWVzdCIaChhDcmVhdGVBc3Nlc3NtZW50UmVzcG9uc2UiGQoXVXBkYXRlQXNzZXNzbWVudFJlcXVlc3QiGgoYVXBkYXRlQXNzZXNzbWVudFJlc3BvbnNlIhkKF0RlbGV0ZUFzc2Vzc21lbnRSZXF1ZXN0IhoKGERlbGV0ZUFzc2Vzc21lbnRSZXNwb25zZSIYChZMaXN0QXNzZXNzbWVudHNSZXF1ZXN0IhkKF0xpc3RBc3Nlc3NtZW50c1Jlc3BvbnNlQrwBChZjb20uc2hhcmVkLm1lc3NhZ2VzLnYxQg9Bc3Nlc3NtZW50UHJvdG9QAVonZ3ltYm8uc3RpeG1hbi5jby9zaGFyZWQvZ2VuL21lc3NhZ2VzL3YxogIDU01YqgISU2hhcmVkLk1lc3NhZ2VzLlYxygISU2hhcmVkXE1lc3NhZ2VzXFYx4gIeU2hhcmVkXE1lc3NhZ2VzXFYxXEdQQk1ldGFkYXRh6gIUU2hhcmVkOjpNZXNzYWdlczo6VjFiBnByb3RvMw");

/**
 * @generated from message shared.messages.v1.GetAssessmentRequest
 */
export type GetAssessmentRequest = Message<"shared.messages.v1.GetAssessmentRequest"> & {
};

/**
 * Describes the message shared.messages.v1.GetAssessmentRequest.
 * Use `create(GetAssessmentRequestSchema)` to create a new message.
 */
export const GetAssessmentRequestSchema: GenMessage<GetAssessmentRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_assessment, 0);

/**
 * @generated from message shared.messages.v1.GetAssessmentResponse
 */
export type GetAssessmentResponse = Message<"shared.messages.v1.GetAssessmentResponse"> & {
};

/**
 * Describes the message shared.messages.v1.GetAssessmentResponse.
 * Use `create(GetAssessmentResponseSchema)` to create a new message.
 */
export const GetAssessmentResponseSchema: GenMessage<GetAssessmentResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_assessment, 1);

/**
 * @generated from message shared.messages.v1.CreateAssessmentRequest
 */
export type CreateAssessmentRequest = Message<"shared.messages.v1.CreateAssessmentRequest"> & {
};

/**
 * Describes the message shared.messages.v1.CreateAssessmentRequest.
 * Use `create(CreateAssessmentRequestSchema)` to create a new message.
 */
export const CreateAssessmentRequestSchema: GenMessage<CreateAssessmentRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_assessment, 2);

/**
 * @generated from message shared.messages.v1.CreateAssessmentResponse
 */
export type CreateAssessmentResponse = Message<"shared.messages.v1.CreateAssessmentResponse"> & {
};

/**
 * Describes the message shared.messages.v1.CreateAssessmentResponse.
 * Use `create(CreateAssessmentResponseSchema)` to create a new message.
 */
export const CreateAssessmentResponseSchema: GenMessage<CreateAssessmentResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_assessment, 3);

/**
 * @generated from message shared.messages.v1.UpdateAssessmentRequest
 */
export type UpdateAssessmentRequest = Message<"shared.messages.v1.UpdateAssessmentRequest"> & {
};

/**
 * Describes the message shared.messages.v1.UpdateAssessmentRequest.
 * Use `create(UpdateAssessmentRequestSchema)` to create a new message.
 */
export const UpdateAssessmentRequestSchema: GenMessage<UpdateAssessmentRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_assessment, 4);

/**
 * @generated from message shared.messages.v1.UpdateAssessmentResponse
 */
export type UpdateAssessmentResponse = Message<"shared.messages.v1.UpdateAssessmentResponse"> & {
};

/**
 * Describes the message shared.messages.v1.UpdateAssessmentResponse.
 * Use `create(UpdateAssessmentResponseSchema)` to create a new message.
 */
export const UpdateAssessmentResponseSchema: GenMessage<UpdateAssessmentResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_assessment, 5);

/**
 * @generated from message shared.messages.v1.DeleteAssessmentRequest
 */
export type DeleteAssessmentRequest = Message<"shared.messages.v1.DeleteAssessmentRequest"> & {
};

/**
 * Describes the message shared.messages.v1.DeleteAssessmentRequest.
 * Use `create(DeleteAssessmentRequestSchema)` to create a new message.
 */
export const DeleteAssessmentRequestSchema: GenMessage<DeleteAssessmentRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_assessment, 6);

/**
 * @generated from message shared.messages.v1.DeleteAssessmentResponse
 */
export type DeleteAssessmentResponse = Message<"shared.messages.v1.DeleteAssessmentResponse"> & {
};

/**
 * Describes the message shared.messages.v1.DeleteAssessmentResponse.
 * Use `create(DeleteAssessmentResponseSchema)` to create a new message.
 */
export const DeleteAssessmentResponseSchema: GenMessage<DeleteAssessmentResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_assessment, 7);

/**
 * @generated from message shared.messages.v1.ListAssessmentsRequest
 */
export type ListAssessmentsRequest = Message<"shared.messages.v1.ListAssessmentsRequest"> & {
};

/**
 * Describes the message shared.messages.v1.ListAssessmentsRequest.
 * Use `create(ListAssessmentsRequestSchema)` to create a new message.
 */
export const ListAssessmentsRequestSchema: GenMessage<ListAssessmentsRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_assessment, 8);

/**
 * @generated from message shared.messages.v1.ListAssessmentsResponse
 */
export type ListAssessmentsResponse = Message<"shared.messages.v1.ListAssessmentsResponse"> & {
};

/**
 * Describes the message shared.messages.v1.ListAssessmentsResponse.
 * Use `create(ListAssessmentsResponseSchema)` to create a new message.
 */
export const ListAssessmentsResponseSchema: GenMessage<ListAssessmentsResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_assessment, 9);

