// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file shared/messages/v1/auth.proto (package shared.messages.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/messages/v1/auth.proto.
 */
export const file_shared_messages_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("Ch1zaGFyZWQvbWVzc2FnZXMvdjEvYXV0aC5wcm90bxISc2hhcmVkLm1lc3NhZ2VzLnYxIi8KBFVzZXISCgoCaWQYASABKAkSDQoFZW1haWwYAiABKAkSDAoEbmFtZRgDIAEoCSIdCgxMb2dpblJlcXVlc3QSDQoFZW1haWwYASABKAkiUAoNTG9naW5SZXNwb25zZRIUCgxhY2Nlc3NfdG9rZW4YASABKAkSFQoNcmVmcmVzaF90b2tlbhgCIAEoCRISCgpleHBpcmVzX2F0GAMgASgDIhcKFUdldEN1cnJlbnRVc2VyUmVxdWVzdCJAChZHZXRDdXJyZW50VXNlclJlc3BvbnNlEiYKBHVzZXIYASABKAsyGC5zaGFyZWQubWVzc2FnZXMudjEuVXNlciIsChNSZWZyZXNoVG9rZW5SZXF1ZXN0EhUKDXJlZnJlc2hfdG9rZW4YASABKAkiVwoUUmVmcmVzaFRva2VuUmVzcG9uc2USFAoMYWNjZXNzX3Rva2VuGAEgASgJEhUKDXJlZnJlc2hfdG9rZW4YAiABKAkSEgoKZXhwaXJlc19hdBgDIAEoA0K2AQoWY29tLnNoYXJlZC5tZXNzYWdlcy52MUIJQXV0aFByb3RvUAFaJ2d5bWJvLnN0aXhtYW4uY28vc2hhcmVkL2dlbi9tZXNzYWdlcy92MaICA1NNWKoCElNoYXJlZC5NZXNzYWdlcy5WMcoCElNoYXJlZFxNZXNzYWdlc1xWMeICHlNoYXJlZFxNZXNzYWdlc1xWMVxHUEJNZXRhZGF0YeoCFFNoYXJlZDo6TWVzc2FnZXM6OlYxYgZwcm90bzM");

/**
 * @generated from message shared.messages.v1.User
 */
export type User = Message<"shared.messages.v1.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;
};

/**
 * Describes the message shared.messages.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_auth, 0);

/**
 * @generated from message shared.messages.v1.LoginRequest
 */
export type LoginRequest = Message<"shared.messages.v1.LoginRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;
};

/**
 * Describes the message shared.messages.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_auth, 1);

/**
 * @generated from message shared.messages.v1.LoginResponse
 */
export type LoginResponse = Message<"shared.messages.v1.LoginResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * @generated from field: int64 expires_at = 3;
   */
  expiresAt: bigint;
};

/**
 * Describes the message shared.messages.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_auth, 2);

/**
 * @generated from message shared.messages.v1.GetCurrentUserRequest
 */
export type GetCurrentUserRequest = Message<"shared.messages.v1.GetCurrentUserRequest"> & {
};

/**
 * Describes the message shared.messages.v1.GetCurrentUserRequest.
 * Use `create(GetCurrentUserRequestSchema)` to create a new message.
 */
export const GetCurrentUserRequestSchema: GenMessage<GetCurrentUserRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_auth, 3);

/**
 * @generated from message shared.messages.v1.GetCurrentUserResponse
 */
export type GetCurrentUserResponse = Message<"shared.messages.v1.GetCurrentUserResponse"> & {
  /**
   * @generated from field: shared.messages.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message shared.messages.v1.GetCurrentUserResponse.
 * Use `create(GetCurrentUserResponseSchema)` to create a new message.
 */
export const GetCurrentUserResponseSchema: GenMessage<GetCurrentUserResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_auth, 4);

/**
 * @generated from message shared.messages.v1.RefreshTokenRequest
 */
export type RefreshTokenRequest = Message<"shared.messages.v1.RefreshTokenRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message shared.messages.v1.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_auth, 5);

/**
 * @generated from message shared.messages.v1.RefreshTokenResponse
 */
export type RefreshTokenResponse = Message<"shared.messages.v1.RefreshTokenResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * @generated from field: int64 expires_at = 3;
   */
  expiresAt: bigint;
};

/**
 * Describes the message shared.messages.v1.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export const RefreshTokenResponseSchema: GenMessage<RefreshTokenResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_auth, 6);

