// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file shared/messages/v1/client.proto (package shared.messages.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Client } from "../../entities/v1/client_pb";
import { file_shared_entities_v1_client } from "../../entities/v1/client_pb";
import type { Sort } from "./share_pb";
import { file_shared_messages_v1_share } from "./share_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/messages/v1/client.proto.
 */
export const file_shared_messages_v1_client: GenFile = /*@__PURE__*/
  fileDesc("Ch9zaGFyZWQvbWVzc2FnZXMvdjEvY2xpZW50LnByb3RvEhJzaGFyZWQubWVzc2FnZXMudjEiHgoQR2V0Q2xpZW50UmVxdWVzdBIKCgJpZBgBIAEoCSI/ChFHZXRDbGllbnRSZXNwb25zZRIqCgZjbGllbnQYASABKAsyGi5zaGFyZWQuZW50aXRpZXMudjEuQ2xpZW50Ir8CChJMaXN0Q2xpZW50c1JlcXVlc3QSDQoFaW5kZXgYASABKAUSDQoFbGltaXQYAiABKAUSDgoGb2Zmc2V0GAMgASgFEkQKB2ZpbHRlcnMYBCADKAsyMy5zaGFyZWQubWVzc2FnZXMudjEuTGlzdENsaWVudHNSZXF1ZXN0LkZpbHRlcnNFbnRyeRI+CgRzb3J0GAUgAygLMjAuc2hhcmVkLm1lc3NhZ2VzLnYxLkxpc3RDbGllbnRzUmVxdWVzdC5Tb3J0RW50cnkaLgoMRmlsdGVyc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEaRQoJU29ydEVudHJ5EgsKA2tleRgBIAEoCRInCgV2YWx1ZRgCIAEoDjIYLnNoYXJlZC5tZXNzYWdlcy52MS5Tb3J0OgI4ASJ+ChNMaXN0Q2xpZW50c1Jlc3BvbnNlEisKB2NsaWVudHMYASADKAsyGi5zaGFyZWQuZW50aXRpZXMudjEuQ2xpZW50Eg0KBXRvdGFsGAIgASgFEgwKBHBhZ2UYAyABKAUSDQoFbGltaXQYBCABKAUSDgoGb2Zmc2V0GAUgASgFIkEKE0NyZWF0ZUNsaWVudFJlcXVlc3QSKgoGY2xpZW50GAEgASgLMhouc2hhcmVkLmVudGl0aWVzLnYxLkNsaWVudCJCChRDcmVhdGVDbGllbnRSZXNwb25zZRIqCgZjbGllbnQYASABKAsyGi5zaGFyZWQuZW50aXRpZXMudjEuQ2xpZW50IkEKE1VwZGF0ZUNsaWVudFJlcXVlc3QSKgoGY2xpZW50GAEgASgLMhouc2hhcmVkLmVudGl0aWVzLnYxLkNsaWVudCJCChRVcGRhdGVDbGllbnRSZXNwb25zZRIqCgZjbGllbnQYASABKAsyGi5zaGFyZWQuZW50aXRpZXMudjEuQ2xpZW50IiEKE0RlbGV0ZUNsaWVudFJlcXVlc3QSCgoCaWQYASABKAkiFgoURGVsZXRlQ2xpZW50UmVzcG9uc2VCuAEKFmNvbS5zaGFyZWQubWVzc2FnZXMudjFCC0NsaWVudFByb3RvUAFaJ2d5bWJvLnN0aXhtYW4uY28vc2hhcmVkL2dlbi9tZXNzYWdlcy92MaICA1NNWKoCElNoYXJlZC5NZXNzYWdlcy5WMcoCElNoYXJlZFxNZXNzYWdlc1xWMeICHlNoYXJlZFxNZXNzYWdlc1xWMVxHUEJNZXRhZGF0YeoCFFNoYXJlZDo6TWVzc2FnZXM6OlYxYgZwcm90bzM", [file_shared_entities_v1_client, file_shared_messages_v1_share]);

/**
 * @generated from message shared.messages.v1.GetClientRequest
 */
export type GetClientRequest = Message<"shared.messages.v1.GetClientRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message shared.messages.v1.GetClientRequest.
 * Use `create(GetClientRequestSchema)` to create a new message.
 */
export const GetClientRequestSchema: GenMessage<GetClientRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_client, 0);

/**
 * @generated from message shared.messages.v1.GetClientResponse
 */
export type GetClientResponse = Message<"shared.messages.v1.GetClientResponse"> & {
  /**
   * @generated from field: shared.entities.v1.Client client = 1;
   */
  client?: Client;
};

/**
 * Describes the message shared.messages.v1.GetClientResponse.
 * Use `create(GetClientResponseSchema)` to create a new message.
 */
export const GetClientResponseSchema: GenMessage<GetClientResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_client, 1);

/**
 * @generated from message shared.messages.v1.ListClientsRequest
 */
export type ListClientsRequest = Message<"shared.messages.v1.ListClientsRequest"> & {
  /**
   * @generated from field: int32 index = 1;
   */
  index: number;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: int32 offset = 3;
   */
  offset: number;

  /**
   * @generated from field: map<string, string> filters = 4;
   */
  filters: { [key: string]: string };

  /**
   * @generated from field: map<string, shared.messages.v1.Sort> sort = 5;
   */
  sort: { [key: string]: Sort };
};

/**
 * Describes the message shared.messages.v1.ListClientsRequest.
 * Use `create(ListClientsRequestSchema)` to create a new message.
 */
export const ListClientsRequestSchema: GenMessage<ListClientsRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_client, 2);

/**
 * @generated from message shared.messages.v1.ListClientsResponse
 */
export type ListClientsResponse = Message<"shared.messages.v1.ListClientsResponse"> & {
  /**
   * @generated from field: repeated shared.entities.v1.Client clients = 1;
   */
  clients: Client[];

  /**
   * @generated from field: int32 total = 2;
   */
  total: number;

  /**
   * @generated from field: int32 page = 3;
   */
  page: number;

  /**
   * @generated from field: int32 limit = 4;
   */
  limit: number;

  /**
   * @generated from field: int32 offset = 5;
   */
  offset: number;
};

/**
 * Describes the message shared.messages.v1.ListClientsResponse.
 * Use `create(ListClientsResponseSchema)` to create a new message.
 */
export const ListClientsResponseSchema: GenMessage<ListClientsResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_client, 3);

/**
 * @generated from message shared.messages.v1.CreateClientRequest
 */
export type CreateClientRequest = Message<"shared.messages.v1.CreateClientRequest"> & {
  /**
   * @generated from field: shared.entities.v1.Client client = 1;
   */
  client?: Client;
};

/**
 * Describes the message shared.messages.v1.CreateClientRequest.
 * Use `create(CreateClientRequestSchema)` to create a new message.
 */
export const CreateClientRequestSchema: GenMessage<CreateClientRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_client, 4);

/**
 * @generated from message shared.messages.v1.CreateClientResponse
 */
export type CreateClientResponse = Message<"shared.messages.v1.CreateClientResponse"> & {
  /**
   * @generated from field: shared.entities.v1.Client client = 1;
   */
  client?: Client;
};

/**
 * Describes the message shared.messages.v1.CreateClientResponse.
 * Use `create(CreateClientResponseSchema)` to create a new message.
 */
export const CreateClientResponseSchema: GenMessage<CreateClientResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_client, 5);

/**
 * @generated from message shared.messages.v1.UpdateClientRequest
 */
export type UpdateClientRequest = Message<"shared.messages.v1.UpdateClientRequest"> & {
  /**
   * @generated from field: shared.entities.v1.Client client = 1;
   */
  client?: Client;
};

/**
 * Describes the message shared.messages.v1.UpdateClientRequest.
 * Use `create(UpdateClientRequestSchema)` to create a new message.
 */
export const UpdateClientRequestSchema: GenMessage<UpdateClientRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_client, 6);

/**
 * @generated from message shared.messages.v1.UpdateClientResponse
 */
export type UpdateClientResponse = Message<"shared.messages.v1.UpdateClientResponse"> & {
  /**
   * @generated from field: shared.entities.v1.Client client = 1;
   */
  client?: Client;
};

/**
 * Describes the message shared.messages.v1.UpdateClientResponse.
 * Use `create(UpdateClientResponseSchema)` to create a new message.
 */
export const UpdateClientResponseSchema: GenMessage<UpdateClientResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_client, 7);

/**
 * @generated from message shared.messages.v1.DeleteClientRequest
 */
export type DeleteClientRequest = Message<"shared.messages.v1.DeleteClientRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message shared.messages.v1.DeleteClientRequest.
 * Use `create(DeleteClientRequestSchema)` to create a new message.
 */
export const DeleteClientRequestSchema: GenMessage<DeleteClientRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_client, 8);

/**
 * @generated from message shared.messages.v1.DeleteClientResponse
 */
export type DeleteClientResponse = Message<"shared.messages.v1.DeleteClientResponse"> & {
};

/**
 * Describes the message shared.messages.v1.DeleteClientResponse.
 * Use `create(DeleteClientResponseSchema)` to create a new message.
 */
export const DeleteClientResponseSchema: GenMessage<DeleteClientResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_client, 9);

