// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file shared/messages/v1/media.proto (package shared.messages.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/messages/v1/media.proto.
 */
export const file_shared_messages_v1_media: GenFile = /*@__PURE__*/
  fileDesc("Ch5zaGFyZWQvbWVzc2FnZXMvdjEvbWVkaWEucHJvdG8SEnNoYXJlZC5tZXNzYWdlcy52MSJ+ChBTdG9yYWdlUmVmZXJlbmNlEj0KEHN0b3JhZ2VfcHJvdmlkZXIYASABKA4yIy5zaGFyZWQubWVzc2FnZXMudjEuU3RvcmFnZVByb3ZpZGVyEg4KBnJlZ2lvbhgCIAEoCRIOCgZidWNrZXQYAyABKAkSCwoDa2V5GAQgASgJIlEKFlNpZ25NZWRpYVVwbG9hZFJlcXVlc3QSEQoJZmlsZV9uYW1lGAEgASgJEhEKCWZpbGVfdHlwZRgCIAEoCRIRCglmaWxlX3NpemUYAyABKAMibgoXU2lnbk1lZGlhVXBsb2FkUmVzcG9uc2USEgoKdXBsb2FkX3VybBgBIAEoCRI/ChFzdG9yYWdlX3JlZmVyZW5jZRgCIAEoCzIkLnNoYXJlZC5tZXNzYWdlcy52MS5TdG9yYWdlUmVmZXJlbmNlKoIBCg9TdG9yYWdlUHJvdmlkZXISIAocU1RPUkFHRV9QUk9WSURFUl9VTlNQRUNJRklFRBAAEhoKFlNUT1JBR0VfUFJPVklERVJfTUlOSU8QARIXChNTVE9SQUdFX1BST1ZJREVSX1MzEAISGAoUU1RPUkFHRV9QUk9WSURFUl9HQ1AQA0K3AQoWY29tLnNoYXJlZC5tZXNzYWdlcy52MUIKTWVkaWFQcm90b1ABWidneW1iby5zdGl4bWFuLmNvL3NoYXJlZC9nZW4vbWVzc2FnZXMvdjGiAgNTTViqAhJTaGFyZWQuTWVzc2FnZXMuVjHKAhJTaGFyZWRcTWVzc2FnZXNcVjHiAh5TaGFyZWRcTWVzc2FnZXNcVjFcR1BCTWV0YWRhdGHqAhRTaGFyZWQ6Ok1lc3NhZ2VzOjpWMWIGcHJvdG8z");

/**
 * @generated from message shared.messages.v1.StorageReference
 */
export type StorageReference = Message<"shared.messages.v1.StorageReference"> & {
  /**
   * @generated from field: shared.messages.v1.StorageProvider storage_provider = 1;
   */
  storageProvider: StorageProvider;

  /**
   * @generated from field: string region = 2;
   */
  region: string;

  /**
   * @generated from field: string bucket = 3;
   */
  bucket: string;

  /**
   * @generated from field: string key = 4;
   */
  key: string;
};

/**
 * Describes the message shared.messages.v1.StorageReference.
 * Use `create(StorageReferenceSchema)` to create a new message.
 */
export const StorageReferenceSchema: GenMessage<StorageReference> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_media, 0);

/**
 * @generated from message shared.messages.v1.SignMediaUploadRequest
 */
export type SignMediaUploadRequest = Message<"shared.messages.v1.SignMediaUploadRequest"> & {
  /**
   * @generated from field: string file_name = 1;
   */
  fileName: string;

  /**
   * @generated from field: string file_type = 2;
   */
  fileType: string;

  /**
   * @generated from field: int64 file_size = 3;
   */
  fileSize: bigint;
};

/**
 * Describes the message shared.messages.v1.SignMediaUploadRequest.
 * Use `create(SignMediaUploadRequestSchema)` to create a new message.
 */
export const SignMediaUploadRequestSchema: GenMessage<SignMediaUploadRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_media, 1);

/**
 * @generated from message shared.messages.v1.SignMediaUploadResponse
 */
export type SignMediaUploadResponse = Message<"shared.messages.v1.SignMediaUploadResponse"> & {
  /**
   * @generated from field: string upload_url = 1;
   */
  uploadUrl: string;

  /**
   * @generated from field: shared.messages.v1.StorageReference storage_reference = 2;
   */
  storageReference?: StorageReference;
};

/**
 * Describes the message shared.messages.v1.SignMediaUploadResponse.
 * Use `create(SignMediaUploadResponseSchema)` to create a new message.
 */
export const SignMediaUploadResponseSchema: GenMessage<SignMediaUploadResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_media, 2);

/**
 * @generated from enum shared.messages.v1.StorageProvider
 */
export enum StorageProvider {
  /**
   * @generated from enum value: STORAGE_PROVIDER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STORAGE_PROVIDER_MINIO = 1;
   */
  MINIO = 1,

  /**
   * @generated from enum value: STORAGE_PROVIDER_S3 = 2;
   */
  S3 = 2,

  /**
   * @generated from enum value: STORAGE_PROVIDER_GCP = 3;
   */
  GCP = 3,
}

/**
 * Describes the enum shared.messages.v1.StorageProvider.
 */
export const StorageProviderSchema: GenEnum<StorageProvider> = /*@__PURE__*/
  enumDesc(file_shared_messages_v1_media, 0);

