// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file shared/messages/v1/organisation.proto (package shared.messages.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Organisation } from "../../entities/v1/organisation_pb";
import { file_shared_entities_v1_organisation } from "../../entities/v1/organisation_pb";
import type { Sort } from "./share_pb";
import { file_shared_messages_v1_share } from "./share_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/messages/v1/organisation.proto.
 */
export const file_shared_messages_v1_organisation: GenFile = /*@__PURE__*/
  fileDesc("CiVzaGFyZWQvbWVzc2FnZXMvdjEvb3JnYW5pc2F0aW9uLnByb3RvEhJzaGFyZWQubWVzc2FnZXMudjEiJAoWR2V0T3JnYW5pc2F0aW9uUmVxdWVzdBIKCgJpZBgBIAEoCSJRChdHZXRPcmdhbmlzYXRpb25SZXNwb25zZRI2CgxvcmdhbmlzYXRpb24YASABKAsyIC5zaGFyZWQuZW50aXRpZXMudjEuT3JnYW5pc2F0aW9uIs4CChdMaXN0T3JnYW5pc2F0aW9uUmVxdWVzdBINCgVpbmRleBgBIAEoBRINCgVsaW1pdBgCIAEoBRIOCgZvZmZzZXQYAyABKAUSSQoHZmlsdGVycxgEIAMoCzI4LnNoYXJlZC5tZXNzYWdlcy52MS5MaXN0T3JnYW5pc2F0aW9uUmVxdWVzdC5GaWx0ZXJzRW50cnkSQwoEc29ydBgFIAMoCzI1LnNoYXJlZC5tZXNzYWdlcy52MS5MaXN0T3JnYW5pc2F0aW9uUmVxdWVzdC5Tb3J0RW50cnkaLgoMRmlsdGVyc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEaRQoJU29ydEVudHJ5EgsKA2tleRgBIAEoCRInCgV2YWx1ZRgCIAEoDjIYLnNoYXJlZC5tZXNzYWdlcy52MS5Tb3J0OgI4ASKPAQoYTGlzdE9yZ2FuaXNhdGlvblJlc3BvbnNlEjcKDW9yZ2FuaXNhdGlvbnMYASADKAsyIC5zaGFyZWQuZW50aXRpZXMudjEuT3JnYW5pc2F0aW9uEg0KBXRvdGFsGAIgASgFEgwKBHBhZ2UYAyABKAUSDQoFbGltaXQYBCABKAUSDgoGb2Zmc2V0GAUgASgFIlMKGUNyZWF0ZU9yZ2FuaXNhdGlvblJlcXVlc3QSNgoMb3JnYW5pc2F0aW9uGAEgASgLMiAuc2hhcmVkLmVudGl0aWVzLnYxLk9yZ2FuaXNhdGlvbiJUChpDcmVhdGVPcmdhbmlzYXRpb25SZXNwb25zZRI2CgxvcmdhbmlzYXRpb24YASABKAsyIC5zaGFyZWQuZW50aXRpZXMudjEuT3JnYW5pc2F0aW9uIlMKGVVwZGF0ZU9yZ2FuaXNhdGlvblJlcXVlc3QSNgoMb3JnYW5pc2F0aW9uGAEgASgLMiAuc2hhcmVkLmVudGl0aWVzLnYxLk9yZ2FuaXNhdGlvbiJUChpVcGRhdGVPcmdhbmlzYXRpb25SZXNwb25zZRI2CgxvcmdhbmlzYXRpb24YASABKAsyIC5zaGFyZWQuZW50aXRpZXMudjEuT3JnYW5pc2F0aW9uIicKGURlbGV0ZU9yZ2FuaXNhdGlvblJlcXVlc3QSCgoCaWQYASABKAkiHAoaRGVsZXRlT3JnYW5pc2F0aW9uUmVzcG9uc2VCvgEKFmNvbS5zaGFyZWQubWVzc2FnZXMudjFCEU9yZ2FuaXNhdGlvblByb3RvUAFaJ2d5bWJvLnN0aXhtYW4uY28vc2hhcmVkL2dlbi9tZXNzYWdlcy92MaICA1NNWKoCElNoYXJlZC5NZXNzYWdlcy5WMcoCElNoYXJlZFxNZXNzYWdlc1xWMeICHlNoYXJlZFxNZXNzYWdlc1xWMVxHUEJNZXRhZGF0YeoCFFNoYXJlZDo6TWVzc2FnZXM6OlYxYgZwcm90bzM", [file_shared_entities_v1_organisation, file_shared_messages_v1_share]);

/**
 * @generated from message shared.messages.v1.GetOrganisationRequest
 */
export type GetOrganisationRequest = Message<"shared.messages.v1.GetOrganisationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message shared.messages.v1.GetOrganisationRequest.
 * Use `create(GetOrganisationRequestSchema)` to create a new message.
 */
export const GetOrganisationRequestSchema: GenMessage<GetOrganisationRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_organisation, 0);

/**
 * @generated from message shared.messages.v1.GetOrganisationResponse
 */
export type GetOrganisationResponse = Message<"shared.messages.v1.GetOrganisationResponse"> & {
  /**
   * @generated from field: shared.entities.v1.Organisation organisation = 1;
   */
  organisation?: Organisation;
};

/**
 * Describes the message shared.messages.v1.GetOrganisationResponse.
 * Use `create(GetOrganisationResponseSchema)` to create a new message.
 */
export const GetOrganisationResponseSchema: GenMessage<GetOrganisationResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_organisation, 1);

/**
 * @generated from message shared.messages.v1.ListOrganisationRequest
 */
export type ListOrganisationRequest = Message<"shared.messages.v1.ListOrganisationRequest"> & {
  /**
   * @generated from field: int32 index = 1;
   */
  index: number;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: int32 offset = 3;
   */
  offset: number;

  /**
   * @generated from field: map<string, string> filters = 4;
   */
  filters: { [key: string]: string };

  /**
   * @generated from field: map<string, shared.messages.v1.Sort> sort = 5;
   */
  sort: { [key: string]: Sort };
};

/**
 * Describes the message shared.messages.v1.ListOrganisationRequest.
 * Use `create(ListOrganisationRequestSchema)` to create a new message.
 */
export const ListOrganisationRequestSchema: GenMessage<ListOrganisationRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_organisation, 2);

/**
 * @generated from message shared.messages.v1.ListOrganisationResponse
 */
export type ListOrganisationResponse = Message<"shared.messages.v1.ListOrganisationResponse"> & {
  /**
   * @generated from field: repeated shared.entities.v1.Organisation organisations = 1;
   */
  organisations: Organisation[];

  /**
   * @generated from field: int32 total = 2;
   */
  total: number;

  /**
   * @generated from field: int32 page = 3;
   */
  page: number;

  /**
   * @generated from field: int32 limit = 4;
   */
  limit: number;

  /**
   * @generated from field: int32 offset = 5;
   */
  offset: number;
};

/**
 * Describes the message shared.messages.v1.ListOrganisationResponse.
 * Use `create(ListOrganisationResponseSchema)` to create a new message.
 */
export const ListOrganisationResponseSchema: GenMessage<ListOrganisationResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_organisation, 3);

/**
 * @generated from message shared.messages.v1.CreateOrganisationRequest
 */
export type CreateOrganisationRequest = Message<"shared.messages.v1.CreateOrganisationRequest"> & {
  /**
   * @generated from field: shared.entities.v1.Organisation organisation = 1;
   */
  organisation?: Organisation;
};

/**
 * Describes the message shared.messages.v1.CreateOrganisationRequest.
 * Use `create(CreateOrganisationRequestSchema)` to create a new message.
 */
export const CreateOrganisationRequestSchema: GenMessage<CreateOrganisationRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_organisation, 4);

/**
 * @generated from message shared.messages.v1.CreateOrganisationResponse
 */
export type CreateOrganisationResponse = Message<"shared.messages.v1.CreateOrganisationResponse"> & {
  /**
   * @generated from field: shared.entities.v1.Organisation organisation = 1;
   */
  organisation?: Organisation;
};

/**
 * Describes the message shared.messages.v1.CreateOrganisationResponse.
 * Use `create(CreateOrganisationResponseSchema)` to create a new message.
 */
export const CreateOrganisationResponseSchema: GenMessage<CreateOrganisationResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_organisation, 5);

/**
 * @generated from message shared.messages.v1.UpdateOrganisationRequest
 */
export type UpdateOrganisationRequest = Message<"shared.messages.v1.UpdateOrganisationRequest"> & {
  /**
   * @generated from field: shared.entities.v1.Organisation organisation = 1;
   */
  organisation?: Organisation;
};

/**
 * Describes the message shared.messages.v1.UpdateOrganisationRequest.
 * Use `create(UpdateOrganisationRequestSchema)` to create a new message.
 */
export const UpdateOrganisationRequestSchema: GenMessage<UpdateOrganisationRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_organisation, 6);

/**
 * @generated from message shared.messages.v1.UpdateOrganisationResponse
 */
export type UpdateOrganisationResponse = Message<"shared.messages.v1.UpdateOrganisationResponse"> & {
  /**
   * @generated from field: shared.entities.v1.Organisation organisation = 1;
   */
  organisation?: Organisation;
};

/**
 * Describes the message shared.messages.v1.UpdateOrganisationResponse.
 * Use `create(UpdateOrganisationResponseSchema)` to create a new message.
 */
export const UpdateOrganisationResponseSchema: GenMessage<UpdateOrganisationResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_organisation, 7);

/**
 * @generated from message shared.messages.v1.DeleteOrganisationRequest
 */
export type DeleteOrganisationRequest = Message<"shared.messages.v1.DeleteOrganisationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message shared.messages.v1.DeleteOrganisationRequest.
 * Use `create(DeleteOrganisationRequestSchema)` to create a new message.
 */
export const DeleteOrganisationRequestSchema: GenMessage<DeleteOrganisationRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_organisation, 8);

/**
 * @generated from message shared.messages.v1.DeleteOrganisationResponse
 */
export type DeleteOrganisationResponse = Message<"shared.messages.v1.DeleteOrganisationResponse"> & {
};

/**
 * Describes the message shared.messages.v1.DeleteOrganisationResponse.
 * Use `create(DeleteOrganisationResponseSchema)` to create a new message.
 */
export const DeleteOrganisationResponseSchema: GenMessage<DeleteOrganisationResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_organisation, 9);

