// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file shared/messages/v1/share.proto (package shared.messages.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file shared/messages/v1/share.proto.
 */
export const file_shared_messages_v1_share: GenFile = /*@__PURE__*/
  fileDesc("Ch5zaGFyZWQvbWVzc2FnZXMvdjEvc2hhcmUucHJvdG8SEnNoYXJlZC5tZXNzYWdlcy52MSo5CgRTb3J0EhQKEFNPUlRfVU5TUEVDSUZJRUQQABIMCghTT1JUX0FTQxABEg0KCVNPUlRfREVTQxACQrcBChZjb20uc2hhcmVkLm1lc3NhZ2VzLnYxQgpTaGFyZVByb3RvUAFaJ2d5bWJvLnN0aXhtYW4uY28vc2hhcmVkL2dlbi9tZXNzYWdlcy92MaICA1NNWKoCElNoYXJlZC5NZXNzYWdlcy5WMcoCElNoYXJlZFxNZXNzYWdlc1xWMeICHlNoYXJlZFxNZXNzYWdlc1xWMVxHUEJNZXRhZGF0YeoCFFNoYXJlZDo6TWVzc2FnZXM6OlYxYgZwcm90bzM");

/**
 * @generated from enum shared.messages.v1.Sort
 */
export enum Sort {
  /**
   * @generated from enum value: SORT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SORT_ASC = 1;
   */
  ASC = 1,

  /**
   * @generated from enum value: SORT_DESC = 2;
   */
  DESC = 2,
}

/**
 * Describes the enum shared.messages.v1.Sort.
 */
export const SortSchema: GenEnum<Sort> = /*@__PURE__*/
  enumDesc(file_shared_messages_v1_share, 0);

