// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file shared/messages/v1/trainer.proto (package shared.messages.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Trainer } from "../../entities/v1/trainer_pb";
import { file_shared_entities_v1_trainer } from "../../entities/v1/trainer_pb";
import type { Sort } from "./share_pb";
import { file_shared_messages_v1_share } from "./share_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/messages/v1/trainer.proto.
 */
export const file_shared_messages_v1_trainer: GenFile = /*@__PURE__*/
  fileDesc("CiBzaGFyZWQvbWVzc2FnZXMvdjEvdHJhaW5lci5wcm90bxISc2hhcmVkLm1lc3NhZ2VzLnYxIh8KEUdldFRyYWluZXJSZXF1ZXN0EgoKAmlkGAEgASgJIkIKEkdldFRyYWluZXJSZXNwb25zZRIsCgd0cmFpbmVyGAEgASgLMhsuc2hhcmVkLmVudGl0aWVzLnYxLlRyYWluZXIiwgIKE0xpc3RUcmFpbmVyc1JlcXVlc3QSDQoFaW5kZXgYASABKAUSDQoFbGltaXQYAiABKAUSDgoGb2Zmc2V0GAMgASgFEkUKB2ZpbHRlcnMYBCADKAsyNC5zaGFyZWQubWVzc2FnZXMudjEuTGlzdFRyYWluZXJzUmVxdWVzdC5GaWx0ZXJzRW50cnkSPwoEc29ydBgFIAMoCzIxLnNoYXJlZC5tZXNzYWdlcy52MS5MaXN0VHJhaW5lcnNSZXF1ZXN0LlNvcnRFbnRyeRouCgxGaWx0ZXJzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ARpFCglTb3J0RW50cnkSCwoDa2V5GAEgASgJEicKBXZhbHVlGAIgASgOMhguc2hhcmVkLm1lc3NhZ2VzLnYxLlNvcnQ6AjgBIoEBChRMaXN0VHJhaW5lcnNSZXNwb25zZRItCgh0cmFpbmVycxgBIAMoCzIbLnNoYXJlZC5lbnRpdGllcy52MS5UcmFpbmVyEg0KBXRvdGFsGAIgASgFEgwKBHBhZ2UYAyABKAUSDQoFbGltaXQYBCABKAUSDgoGb2Zmc2V0GAUgASgFIkQKFENyZWF0ZVRyYWluZXJSZXF1ZXN0EiwKB3RyYWluZXIYASABKAsyGy5zaGFyZWQuZW50aXRpZXMudjEuVHJhaW5lciJFChVDcmVhdGVUcmFpbmVyUmVzcG9uc2USLAoHdHJhaW5lchgBIAEoCzIbLnNoYXJlZC5lbnRpdGllcy52MS5UcmFpbmVyIkQKFFVwZGF0ZVRyYWluZXJSZXF1ZXN0EiwKB3RyYWluZXIYASABKAsyGy5zaGFyZWQuZW50aXRpZXMudjEuVHJhaW5lciJFChVVcGRhdGVUcmFpbmVyUmVzcG9uc2USLAoHdHJhaW5lchgBIAEoCzIbLnNoYXJlZC5lbnRpdGllcy52MS5UcmFpbmVyIiIKFERlbGV0ZVRyYWluZXJSZXF1ZXN0EgoKAmlkGAEgASgJIhcKFURlbGV0ZVRyYWluZXJSZXNwb25zZUK5AQoWY29tLnNoYXJlZC5tZXNzYWdlcy52MUIMVHJhaW5lclByb3RvUAFaJ2d5bWJvLnN0aXhtYW4uY28vc2hhcmVkL2dlbi9tZXNzYWdlcy92MaICA1NNWKoCElNoYXJlZC5NZXNzYWdlcy5WMcoCElNoYXJlZFxNZXNzYWdlc1xWMeICHlNoYXJlZFxNZXNzYWdlc1xWMVxHUEJNZXRhZGF0YeoCFFNoYXJlZDo6TWVzc2FnZXM6OlYxYgZwcm90bzM", [file_shared_entities_v1_trainer, file_shared_messages_v1_share]);

/**
 * @generated from message shared.messages.v1.GetTrainerRequest
 */
export type GetTrainerRequest = Message<"shared.messages.v1.GetTrainerRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message shared.messages.v1.GetTrainerRequest.
 * Use `create(GetTrainerRequestSchema)` to create a new message.
 */
export const GetTrainerRequestSchema: GenMessage<GetTrainerRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_trainer, 0);

/**
 * @generated from message shared.messages.v1.GetTrainerResponse
 */
export type GetTrainerResponse = Message<"shared.messages.v1.GetTrainerResponse"> & {
  /**
   * @generated from field: shared.entities.v1.Trainer trainer = 1;
   */
  trainer?: Trainer;
};

/**
 * Describes the message shared.messages.v1.GetTrainerResponse.
 * Use `create(GetTrainerResponseSchema)` to create a new message.
 */
export const GetTrainerResponseSchema: GenMessage<GetTrainerResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_trainer, 1);

/**
 * @generated from message shared.messages.v1.ListTrainersRequest
 */
export type ListTrainersRequest = Message<"shared.messages.v1.ListTrainersRequest"> & {
  /**
   * @generated from field: int32 index = 1;
   */
  index: number;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: int32 offset = 3;
   */
  offset: number;

  /**
   * @generated from field: map<string, string> filters = 4;
   */
  filters: { [key: string]: string };

  /**
   * @generated from field: map<string, shared.messages.v1.Sort> sort = 5;
   */
  sort: { [key: string]: Sort };
};

/**
 * Describes the message shared.messages.v1.ListTrainersRequest.
 * Use `create(ListTrainersRequestSchema)` to create a new message.
 */
export const ListTrainersRequestSchema: GenMessage<ListTrainersRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_trainer, 2);

/**
 * @generated from message shared.messages.v1.ListTrainersResponse
 */
export type ListTrainersResponse = Message<"shared.messages.v1.ListTrainersResponse"> & {
  /**
   * @generated from field: repeated shared.entities.v1.Trainer trainers = 1;
   */
  trainers: Trainer[];

  /**
   * @generated from field: int32 total = 2;
   */
  total: number;

  /**
   * @generated from field: int32 page = 3;
   */
  page: number;

  /**
   * @generated from field: int32 limit = 4;
   */
  limit: number;

  /**
   * @generated from field: int32 offset = 5;
   */
  offset: number;
};

/**
 * Describes the message shared.messages.v1.ListTrainersResponse.
 * Use `create(ListTrainersResponseSchema)` to create a new message.
 */
export const ListTrainersResponseSchema: GenMessage<ListTrainersResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_trainer, 3);

/**
 * @generated from message shared.messages.v1.CreateTrainerRequest
 */
export type CreateTrainerRequest = Message<"shared.messages.v1.CreateTrainerRequest"> & {
  /**
   * @generated from field: shared.entities.v1.Trainer trainer = 1;
   */
  trainer?: Trainer;
};

/**
 * Describes the message shared.messages.v1.CreateTrainerRequest.
 * Use `create(CreateTrainerRequestSchema)` to create a new message.
 */
export const CreateTrainerRequestSchema: GenMessage<CreateTrainerRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_trainer, 4);

/**
 * @generated from message shared.messages.v1.CreateTrainerResponse
 */
export type CreateTrainerResponse = Message<"shared.messages.v1.CreateTrainerResponse"> & {
  /**
   * @generated from field: shared.entities.v1.Trainer trainer = 1;
   */
  trainer?: Trainer;
};

/**
 * Describes the message shared.messages.v1.CreateTrainerResponse.
 * Use `create(CreateTrainerResponseSchema)` to create a new message.
 */
export const CreateTrainerResponseSchema: GenMessage<CreateTrainerResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_trainer, 5);

/**
 * @generated from message shared.messages.v1.UpdateTrainerRequest
 */
export type UpdateTrainerRequest = Message<"shared.messages.v1.UpdateTrainerRequest"> & {
  /**
   * @generated from field: shared.entities.v1.Trainer trainer = 1;
   */
  trainer?: Trainer;
};

/**
 * Describes the message shared.messages.v1.UpdateTrainerRequest.
 * Use `create(UpdateTrainerRequestSchema)` to create a new message.
 */
export const UpdateTrainerRequestSchema: GenMessage<UpdateTrainerRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_trainer, 6);

/**
 * @generated from message shared.messages.v1.UpdateTrainerResponse
 */
export type UpdateTrainerResponse = Message<"shared.messages.v1.UpdateTrainerResponse"> & {
  /**
   * @generated from field: shared.entities.v1.Trainer trainer = 1;
   */
  trainer?: Trainer;
};

/**
 * Describes the message shared.messages.v1.UpdateTrainerResponse.
 * Use `create(UpdateTrainerResponseSchema)` to create a new message.
 */
export const UpdateTrainerResponseSchema: GenMessage<UpdateTrainerResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_trainer, 7);

/**
 * @generated from message shared.messages.v1.DeleteTrainerRequest
 */
export type DeleteTrainerRequest = Message<"shared.messages.v1.DeleteTrainerRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message shared.messages.v1.DeleteTrainerRequest.
 * Use `create(DeleteTrainerRequestSchema)` to create a new message.
 */
export const DeleteTrainerRequestSchema: GenMessage<DeleteTrainerRequest> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_trainer, 8);

/**
 * @generated from message shared.messages.v1.DeleteTrainerResponse
 */
export type DeleteTrainerResponse = Message<"shared.messages.v1.DeleteTrainerResponse"> & {
};

/**
 * Describes the message shared.messages.v1.DeleteTrainerResponse.
 * Use `create(DeleteTrainerResponseSchema)` to create a new message.
 */
export const DeleteTrainerResponseSchema: GenMessage<DeleteTrainerResponse> = /*@__PURE__*/
  messageDesc(file_shared_messages_v1_trainer, 9);

