// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file gateways/trainer/v1/trainer_gateway.proto (package gateways.trainer.v1, syntax proto3)
/* eslint-disable */

import { TrainerGatewayService } from "./trainer_gateway_pb";

/**
 * @generated from rpc gateways.trainer.v1.TrainerGatewayService.GetUser
 */
export const getUser = TrainerGatewayService.method.getUser;
