// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file gateways/trainer/v1/trainer_gateway.proto (package gateways.trainer.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gateways/trainer/v1/trainer_gateway.proto.
 */
export const file_gateways_trainer_v1_trainer_gateway: GenFile = /*@__PURE__*/
  fileDesc("CilnYXRld2F5cy90cmFpbmVyL3YxL3RyYWluZXJfZ2F0ZXdheS5wcm90bxITZ2F0ZXdheXMudHJhaW5lci52MSIQCg5HZXRVc2VyUmVxdWVzdCIRCg9HZXRVc2VyUmVzcG9uc2UybwoVVHJhaW5lckdhdGV3YXlTZXJ2aWNlElYKB0dldFVzZXISIy5nYXRld2F5cy50cmFpbmVyLnYxLkdldFVzZXJSZXF1ZXN0GiQuZ2F0ZXdheXMudHJhaW5lci52MS5HZXRVc2VyUmVzcG9uc2UiAELOAQoXY29tLmdhdGV3YXlzLnRyYWluZXIudjFCE1RyYWluZXJHYXRld2F5UHJvdG9QAVowZ3ltYm8uc3RpeG1hbi5jby90cmFpbmVyX2dhdGV3YXkvZ2VuL2dhdGV3YXlzL3YxogIDR1RYqgITR2F0ZXdheXMuVHJhaW5lci5WMcoCE0dhdGV3YXlzXFRyYWluZXJcVjHiAh9HYXRld2F5c1xUcmFpbmVyXFYxXEdQQk1ldGFkYXRh6gIVR2F0ZXdheXM6OlRyYWluZXI6OlYxYgZwcm90bzM");

/**
 * @generated from message gateways.trainer.v1.GetUserRequest
 */
export type GetUserRequest = Message<"gateways.trainer.v1.GetUserRequest"> & {
};

/**
 * Describes the message gateways.trainer.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_gateways_trainer_v1_trainer_gateway, 0);

/**
 * @generated from message gateways.trainer.v1.GetUserResponse
 */
export type GetUserResponse = Message<"gateways.trainer.v1.GetUserResponse"> & {
};

/**
 * Describes the message gateways.trainer.v1.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> = /*@__PURE__*/
  messageDesc(file_gateways_trainer_v1_trainer_gateway, 1);

/**
 * @generated from service gateways.trainer.v1.TrainerGatewayService
 */
export const TrainerGatewayService: GenService<{
  /**
   * @generated from rpc gateways.trainer.v1.TrainerGatewayService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gateways_trainer_v1_trainer_gateway, 0);

