// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file shared/entities/v1/assessment.proto (package shared.entities.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/entities/v1/assessment.proto.
 */
export const file_shared_entities_v1_assessment: GenFile = /*@__PURE__*/
  fileDesc("CiNzaGFyZWQvZW50aXRpZXMvdjEvYXNzZXNzbWVudC5wcm90bxISc2hhcmVkLmVudGl0aWVzLnYxIrwCCgpBc3Nlc3NtZW50EgoKAmlkGAEgASgJEhEKCWNsaWVudF9pZBgCIAEoCRISCgp0cmFpbmVyX2lkGAMgASgJEhwKD29yZ2FuaXNhdGlvbl9pZBgEIAEoCUgAiAEBEigKBGRhdGUYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEg8KB2NvbW1lbnQYBiABKAkSLgoKY3JlYXRlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgIIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKZGVsZXRlZF9hdBgJIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCEgoQX29yZ2FuaXNhdGlvbl9pZEK8AQoWY29tLnNoYXJlZC5lbnRpdGllcy52MUIPQXNzZXNzbWVudFByb3RvUAFaJ2d5bWJvLnN0aXhtYW4uY28vc2hhcmVkL2dlbi9lbnRpdGllcy92MaICA1NFWKoCElNoYXJlZC5FbnRpdGllcy5WMcoCElNoYXJlZFxFbnRpdGllc1xWMeICHlNoYXJlZFxFbnRpdGllc1xWMVxHUEJNZXRhZGF0YeoCFFNoYXJlZDo6RW50aXRpZXM6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message shared.entities.v1.Assessment
 */
export type Assessment = Message<"shared.entities.v1.Assessment"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string client_id = 2;
   */
  clientId: string;

  /**
   * @generated from field: string trainer_id = 3;
   */
  trainerId: string;

  /**
   * @generated from field: optional string organisation_id = 4;
   */
  organisationId?: string;

  /**
   * @generated from field: google.protobuf.Timestamp date = 5;
   */
  date?: Timestamp;

  /**
   * @generated from field: string comment = 6;
   */
  comment: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 8;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp deleted_at = 9;
   */
  deletedAt?: Timestamp;
};

/**
 * Describes the message shared.entities.v1.Assessment.
 * Use `create(AssessmentSchema)` to create a new message.
 */
export const AssessmentSchema: GenMessage<Assessment> = /*@__PURE__*/
  messageDesc(file_shared_entities_v1_assessment, 0);

