// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file shared/entities/v1/exercise.proto (package shared.entities.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/entities/v1/exercise.proto.
 */
export const file_shared_entities_v1_exercise: GenFile = /*@__PURE__*/
  fileDesc("CiFzaGFyZWQvZW50aXRpZXMvdjEvZXhlcmNpc2UucHJvdG8SEnNoYXJlZC5lbnRpdGllcy52MSLdAgoIRXhlcmNpc2USCgoCaWQYASABKAkSEQoJY2xpZW50X2lkGAIgASgJEhoKDWFzc2Vzc21lbnRfaWQYAyABKAlIAIgBARIQCghtZWRpYV9pZBgEIAEoCRIMCgRuYW1lGAUgASgJEhMKC2Rlc2NyaXB0aW9uGAYgASgJEi4KBHR5cGUYByABKA4yIC5zaGFyZWQuZW50aXRpZXMudjEuRXhlcmNpc2VUeXBlEg8KB2NvbW1lbnQYCCABKAkSLgoKY3JlYXRlZF9hdBgJIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgKIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKZGVsZXRlZF9hdBgLIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCEAoOX2Fzc2Vzc21lbnRfaWQi2AEKC05ld0V4ZXJjaXNlEgwKBG5hbWUYASABKAkSEQoJY2xpZW50X2lkGAIgASgJEhoKDWFzc2Vzc21lbnRfaWQYAyABKAlIAIgBARIYCgtkZXNjcmlwdGlvbhgEIAEoCUgBiAEBEi4KBHR5cGUYBSABKA4yIC5zaGFyZWQuZW50aXRpZXMudjEuRXhlcmNpc2VUeXBlEhQKB2NvbW1lbnQYBiABKAlIAogBAUIQCg5fYXNzZXNzbWVudF9pZEIOCgxfZGVzY3JpcHRpb25CCgoIX2NvbW1lbnQqegoMRXhlcmNpc2VUeXBlEh0KGUVYRVJDSVNFX1RZUEVfVU5TUEVDSUZJRUQQABIXChNFWEVSQ0lTRV9UWVBFX1NRVUFUEAESFwoTRVhFUkNJU0VfVFlQRV9MVU5HRRACEhkKFUVYRVJDSVNFX1RZUEVfUFVTSF9VUBADQroBChZjb20uc2hhcmVkLmVudGl0aWVzLnYxQg1FeGVyY2lzZVByb3RvUAFaJ2d5bWJvLnN0aXhtYW4uY28vc2hhcmVkL2dlbi9lbnRpdGllcy92MaICA1NFWKoCElNoYXJlZC5FbnRpdGllcy5WMcoCElNoYXJlZFxFbnRpdGllc1xWMeICHlNoYXJlZFxFbnRpdGllc1xWMVxHUEJNZXRhZGF0YeoCFFNoYXJlZDo6RW50aXRpZXM6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message shared.entities.v1.Exercise
 */
export type Exercise = Message<"shared.entities.v1.Exercise"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string client_id = 2;
   */
  clientId: string;

  /**
   * @generated from field: optional string assessment_id = 3;
   */
  assessmentId?: string;

  /**
   * @generated from field: string media_id = 4;
   */
  mediaId: string;

  /**
   * @generated from field: string name = 5;
   */
  name: string;

  /**
   * @generated from field: string description = 6;
   */
  description: string;

  /**
   * @generated from field: shared.entities.v1.ExerciseType type = 7;
   */
  type: ExerciseType;

  /**
   * @generated from field: string comment = 8;
   */
  comment: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 9;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 10;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp deleted_at = 11;
   */
  deletedAt?: Timestamp;
};

/**
 * Describes the message shared.entities.v1.Exercise.
 * Use `create(ExerciseSchema)` to create a new message.
 */
export const ExerciseSchema: GenMessage<Exercise> = /*@__PURE__*/
  messageDesc(file_shared_entities_v1_exercise, 0);

/**
 * @generated from message shared.entities.v1.NewExercise
 */
export type NewExercise = Message<"shared.entities.v1.NewExercise"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string client_id = 2;
   */
  clientId: string;

  /**
   * @generated from field: optional string assessment_id = 3;
   */
  assessmentId?: string;

  /**
   * @generated from field: optional string description = 4;
   */
  description?: string;

  /**
   * @generated from field: shared.entities.v1.ExerciseType type = 5;
   */
  type: ExerciseType;

  /**
   * @generated from field: optional string comment = 6;
   */
  comment?: string;
};

/**
 * Describes the message shared.entities.v1.NewExercise.
 * Use `create(NewExerciseSchema)` to create a new message.
 */
export const NewExerciseSchema: GenMessage<NewExercise> = /*@__PURE__*/
  messageDesc(file_shared_entities_v1_exercise, 1);

/**
 * @generated from enum shared.entities.v1.ExerciseType
 */
export enum ExerciseType {
  /**
   * @generated from enum value: EXERCISE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: EXERCISE_TYPE_SQUAT = 1;
   */
  SQUAT = 1,

  /**
   * @generated from enum value: EXERCISE_TYPE_LUNGE = 2;
   */
  LUNGE = 2,

  /**
   * @generated from enum value: EXERCISE_TYPE_PUSH_UP = 3;
   */
  PUSH_UP = 3,
}

/**
 * Describes the enum shared.entities.v1.ExerciseType.
 */
export const ExerciseTypeSchema: GenEnum<ExerciseType> = /*@__PURE__*/
  enumDesc(file_shared_entities_v1_exercise, 0);

