// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file shared/entities/v1/pose_detection.proto (package shared.entities.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file shared/entities/v1/pose_detection.proto.
 */
export const file_shared_entities_v1_pose_detection: GenFile = /*@__PURE__*/
  fileDesc("CidzaGFyZWQvZW50aXRpZXMvdjEvcG9zZV9kZXRlY3Rpb24ucHJvdG8SEnNoYXJlZC5lbnRpdGllcy52MSrJAQobTWVkaWFQaXBlUG9zZURldGVjdGlvbk1vZGVsEi4KKk1FRElBUElQRV9QT1NFX0RFVEVDVElPTl9NT0RFTF9VTlNQRUNJRklFRBAAEicKI01FRElBUElQRV9QT1NFX0RFVEVDVElPTl9NT0RFTF9MSVRFEAESJwojTUVESUFQSVBFX1BPU0VfREVURUNUSU9OX01PREVMX0ZVTEwQAhIoCiRNRURJQVBJUEVfUE9TRV9ERVRFQ1RJT05fTU9ERUxfSEVBVlkQA0K/AQoWY29tLnNoYXJlZC5lbnRpdGllcy52MUISUG9zZURldGVjdGlvblByb3RvUAFaJ2d5bWJvLnN0aXhtYW4uY28vc2hhcmVkL2dlbi9lbnRpdGllcy92MaICA1NFWKoCElNoYXJlZC5FbnRpdGllcy5WMcoCElNoYXJlZFxFbnRpdGllc1xWMeICHlNoYXJlZFxFbnRpdGllc1xWMVxHUEJNZXRhZGF0YeoCFFNoYXJlZDo6RW50aXRpZXM6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from enum shared.entities.v1.MediaPipePoseDetectionModel
 */
export enum MediaPipePoseDetectionModel {
  /**
   * @generated from enum value: MEDIAPIPE_POSE_DETECTION_MODEL_UNSPECIFIED = 0;
   */
  MEDIAPIPE_POSE_DETECTION_MODEL_UNSPECIFIED = 0,

  /**
   * @generated from enum value: MEDIAPIPE_POSE_DETECTION_MODEL_LITE = 1;
   */
  MEDIAPIPE_POSE_DETECTION_MODEL_LITE = 1,

  /**
   * @generated from enum value: MEDIAPIPE_POSE_DETECTION_MODEL_FULL = 2;
   */
  MEDIAPIPE_POSE_DETECTION_MODEL_FULL = 2,

  /**
   * @generated from enum value: MEDIAPIPE_POSE_DETECTION_MODEL_HEAVY = 3;
   */
  MEDIAPIPE_POSE_DETECTION_MODEL_HEAVY = 3,
}

/**
 * Describes the enum shared.entities.v1.MediaPipePoseDetectionModel.
 */
export const MediaPipePoseDetectionModelSchema: GenEnum<MediaPipePoseDetectionModel> = /*@__PURE__*/
  enumDesc(file_shared_entities_v1_pose_detection, 0);

