// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file shared/entities/v1/trainer.proto (package shared.entities.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/entities/v1/trainer.proto.
 */
export const file_shared_entities_v1_trainer: GenFile = /*@__PURE__*/
  fileDesc("CiBzaGFyZWQvZW50aXRpZXMvdjEvdHJhaW5lci5wcm90bxISc2hhcmVkLmVudGl0aWVzLnYxIpUCCgdUcmFpbmVyEgoKAmlkGAEgASgJEg0KBWVtYWlsGAIgASgJEhEKCWZ1bGxfbmFtZRgDIAEoCRIXCgpmaXJzdF9uYW1lGAQgASgJSACIAQESFgoJbGFzdF9uYW1lGAUgASgJSAGIAQESLgoKY3JlYXRlZF9hdBgJIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgKIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKZGVsZXRlZF9hdBgLIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCDQoLX2ZpcnN0X25hbWVCDAoKX2xhc3RfbmFtZUK5AQoWY29tLnNoYXJlZC5lbnRpdGllcy52MUIMVHJhaW5lclByb3RvUAFaJ2d5bWJvLnN0aXhtYW4uY28vc2hhcmVkL2dlbi9lbnRpdGllcy92MaICA1NFWKoCElNoYXJlZC5FbnRpdGllcy5WMcoCElNoYXJlZFxFbnRpdGllc1xWMeICHlNoYXJlZFxFbnRpdGllc1xWMVxHUEJNZXRhZGF0YeoCFFNoYXJlZDo6RW50aXRpZXM6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message shared.entities.v1.Trainer
 */
export type Trainer = Message<"shared.entities.v1.Trainer"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string full_name = 3;
   */
  fullName: string;

  /**
   * @generated from field: optional string first_name = 4;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 5;
   */
  lastName?: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 9;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 10;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp deleted_at = 11;
   */
  deletedAt?: Timestamp;
};

/**
 * Describes the message shared.entities.v1.Trainer.
 * Use `create(TrainerSchema)` to create a new message.
 */
export const TrainerSchema: GenMessage<Trainer> = /*@__PURE__*/
  messageDesc(file_shared_entities_v1_trainer, 0);

