// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file gateways/organisation/v1/organisation_gateway.proto (package gateways.organisation.v1, syntax proto3)
/* eslint-disable */

import { OrganisationGatewayService } from "./organisation_gateway_pb";

/**
 * @generated from rpc gateways.organisation.v1.OrganisationGatewayService.GetOrganisation
 */
export const getOrganisation = OrganisationGatewayService.method.getOrganisation;
