// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file gateways/organisation/v1/organisation_gateway.proto (package gateways.organisation.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gateways/organisation/v1/organisation_gateway.proto.
 */
export const file_gateways_organisation_v1_organisation_gateway: GenFile = /*@__PURE__*/
  fileDesc("CjNnYXRld2F5cy9vcmdhbmlzYXRpb24vdjEvb3JnYW5pc2F0aW9uX2dhdGV3YXkucHJvdG8SGGdhdGV3YXlzLm9yZ2FuaXNhdGlvbi52MSIYChZHZXRPcmdhbmlzYXRpb25SZXF1ZXN0IhkKF0dldE9yZ2FuaXNhdGlvblJlc3BvbnNlMpYBChpPcmdhbmlzYXRpb25HYXRld2F5U2VydmljZRJ4Cg9HZXRPcmdhbmlzYXRpb24SMC5nYXRld2F5cy5vcmdhbmlzYXRpb24udjEuR2V0T3JnYW5pc2F0aW9uUmVxdWVzdBoxLmdhdGV3YXlzLm9yZ2FuaXNhdGlvbi52MS5HZXRPcmdhbmlzYXRpb25SZXNwb25zZSIAQvEBChxjb20uZ2F0ZXdheXMub3JnYW5pc2F0aW9uLnYxQhhPcmdhbmlzYXRpb25HYXRld2F5UHJvdG9QAVo1Z3ltYm8uc3RpeG1hbi5jby9vcmdhbmlzYXRpb25fZ2F0ZXdheS9nZW4vZ2F0ZXdheXMvdjGiAgNHT1iqAhhHYXRld2F5cy5PcmdhbmlzYXRpb24uVjHKAhhHYXRld2F5c1xPcmdhbmlzYXRpb25cVjHiAiRHYXRld2F5c1xPcmdhbmlzYXRpb25cVjFcR1BCTWV0YWRhdGHqAhpHYXRld2F5czo6T3JnYW5pc2F0aW9uOjpWMWIGcHJvdG8z");

/**
 * @generated from message gateways.organisation.v1.GetOrganisationRequest
 */
export type GetOrganisationRequest = Message<"gateways.organisation.v1.GetOrganisationRequest"> & {
};

/**
 * Describes the message gateways.organisation.v1.GetOrganisationRequest.
 * Use `create(GetOrganisationRequestSchema)` to create a new message.
 */
export const GetOrganisationRequestSchema: GenMessage<GetOrganisationRequest> = /*@__PURE__*/
  messageDesc(file_gateways_organisation_v1_organisation_gateway, 0);

/**
 * @generated from message gateways.organisation.v1.GetOrganisationResponse
 */
export type GetOrganisationResponse = Message<"gateways.organisation.v1.GetOrganisationResponse"> & {
};

/**
 * Describes the message gateways.organisation.v1.GetOrganisationResponse.
 * Use `create(GetOrganisationResponseSchema)` to create a new message.
 */
export const GetOrganisationResponseSchema: GenMessage<GetOrganisationResponse> = /*@__PURE__*/
  messageDesc(file_gateways_organisation_v1_organisation_gateway, 1);

/**
 * @generated from service gateways.organisation.v1.OrganisationGatewayService
 */
export const OrganisationGatewayService: GenService<{
  /**
   * @generated from rpc gateways.organisation.v1.OrganisationGatewayService.GetOrganisation
   */
  getOrganisation: {
    methodKind: "unary";
    input: typeof GetOrganisationRequestSchema;
    output: typeof GetOrganisationResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gateways_organisation_v1_organisation_gateway, 0);

