// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file gateways/client/v1/client_gateway.proto (package gateways.client.v1, syntax proto3)
/* eslint-disable */

import { ClientGatewayService } from "./client_gateway_pb";

/**
 * @generated from rpc gateways.client.v1.ClientGatewayService.GetClient
 */
export const getClient = ClientGatewayService.method.getClient;
