// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file gateways/client/v1/client_gateway.proto (package gateways.client.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Client } from "../../../shared/entities/v1/client_pb";
import { file_shared_entities_v1_client } from "../../../shared/entities/v1/client_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gateways/client/v1/client_gateway.proto.
 */
export const file_gateways_client_v1_client_gateway: GenFile = /*@__PURE__*/
  fileDesc("CidnYXRld2F5cy9jbGllbnQvdjEvY2xpZW50X2dhdGV3YXkucHJvdG8SEmdhdGV3YXlzLmNsaWVudC52MSISChBHZXRDbGllbnRSZXF1ZXN0Ij8KEUdldENsaWVudFJlc3BvbnNlEioKBmNsaWVudBgBIAEoCzIaLnNoYXJlZC5lbnRpdGllcy52MS5DbGllbnQycgoUQ2xpZW50R2F0ZXdheVNlcnZpY2USWgoJR2V0Q2xpZW50EiQuZ2F0ZXdheXMuY2xpZW50LnYxLkdldENsaWVudFJlcXVlc3QaJS5nYXRld2F5cy5jbGllbnQudjEuR2V0Q2xpZW50UmVzcG9uc2UiAELHAQoWY29tLmdhdGV3YXlzLmNsaWVudC52MUISQ2xpZW50R2F0ZXdheVByb3RvUAFaL2d5bWJvLnN0aXhtYW4uY28vY2xpZW50X2dhdGV3YXkvZ2VuL2dhdGV3YXlzL3YxogIDR0NYqgISR2F0ZXdheXMuQ2xpZW50LlYxygISR2F0ZXdheXNcQ2xpZW50XFYx4gIeR2F0ZXdheXNcQ2xpZW50XFYxXEdQQk1ldGFkYXRh6gIUR2F0ZXdheXM6OkNsaWVudDo6VjFiBnByb3RvMw", [file_shared_entities_v1_client]);

/**
 * @generated from message gateways.client.v1.GetClientRequest
 */
export type GetClientRequest = Message<"gateways.client.v1.GetClientRequest"> & {
};

/**
 * Describes the message gateways.client.v1.GetClientRequest.
 * Use `create(GetClientRequestSchema)` to create a new message.
 */
export const GetClientRequestSchema: GenMessage<GetClientRequest> = /*@__PURE__*/
  messageDesc(file_gateways_client_v1_client_gateway, 0);

/**
 * @generated from message gateways.client.v1.GetClientResponse
 */
export type GetClientResponse = Message<"gateways.client.v1.GetClientResponse"> & {
  /**
   * @generated from field: shared.entities.v1.Client client = 1;
   */
  client?: Client;
};

/**
 * Describes the message gateways.client.v1.GetClientResponse.
 * Use `create(GetClientResponseSchema)` to create a new message.
 */
export const GetClientResponseSchema: GenMessage<GetClientResponse> = /*@__PURE__*/
  messageDesc(file_gateways_client_v1_client_gateway, 1);

/**
 * @generated from service gateways.client.v1.ClientGatewayService
 */
export const ClientGatewayService: GenService<{
  /**
   * @generated from rpc gateways.client.v1.ClientGatewayService.GetClient
   */
  getClient: {
    methodKind: "unary";
    input: typeof GetClientRequestSchema;
    output: typeof GetClientResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gateways_client_v1_client_gateway, 0);

